# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyboardx.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

"""


    mathKeyboard.py
    This program, contains 27 widely used math symbols and lets you to copy and use them easily.
    Ege Guler - Galatasaray University
    05/27/2022


"""

from PyQt5 import QtCore, QtGui, QtWidgets
import time

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(780, 420)
        MainWindow.setMaximumSize(QtCore.QSize(780, 420))
        MainWindow.setMouseTracking(False)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("color: rgb(8, 0, 255);\n"
                                 "background-color: rgb(255, 253, 254);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.p1 = QtWidgets.QPushButton(self.centralwidget ,clicked = lambda: self.press_it(1))
        self.p1.setGeometry(QtCore.QRect(30, 120, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p1.setFont(font)
        self.p1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p1.setIconSize(QtCore.QSize(16, 16))
        self.p1.setObjectName("p1")
        self.p2 = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it(2))

        self.p2.setGeometry(QtCore.QRect(110, 120, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p2.setFont(font)
        self.p2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p2.setIconSize(QtCore.QSize(16, 16))
        self.p2.setObjectName("p2")
        self.p6 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(7))
        self.p6.setGeometry(QtCore.QRect(430, 120, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p6.setFont(font)
        self.p6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p6.setIconSize(QtCore.QSize(16, 16))
        self.p6.setObjectName("p6")
        self.p5 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(5))
        self.p5.setGeometry(QtCore.QRect(350, 120, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p5.setFont(font)
        self.p5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p5.setIconSize(QtCore.QSize(16, 16))
        self.p5.setObjectName("p5")
        self.p4 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(4))
        self.p4.setGeometry(QtCore.QRect(270, 120, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p4.setFont(font)
        self.p4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p4.setIconSize(QtCore.QSize(16, 16))
        self.p4.setObjectName("p4")
        self.p3 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(3))
        self.p3.setGeometry(QtCore.QRect(190, 120, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p3.setFont(font)
        self.p3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p3.setIconSize(QtCore.QSize(16, 16))
        self.p3.setObjectName("p3")
        self.p8 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(8))
        self.p8.setGeometry(QtCore.QRect(590, 120, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p8.setFont(font)
        self.p8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p8.setIconSize(QtCore.QSize(16, 16))
        self.p8.setObjectName("p8")
        self.p9 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(9))
        self.p9.setGeometry(QtCore.QRect(670, 120, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p9.setFont(font)
        self.p9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p9.setIconSize(QtCore.QSize(16, 16))
        self.p9.setObjectName("p9")
        self.p7 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(6))
        self.p7.setGeometry(QtCore.QRect(510, 120, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p7.setFont(font)
        self.p7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p7.setIconSize(QtCore.QSize(16, 16))
        self.p7.setObjectName("p7")
        self.p10 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(10))
        self.p10.setGeometry(QtCore.QRect(30, 200, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p10.setFont(font)
        self.p10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p10.setIconSize(QtCore.QSize(16, 16))
        self.p10.setObjectName("p10")
        self.p18 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(18))
        self.p18.setGeometry(QtCore.QRect(670, 200, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p18.setFont(font)
        self.p18.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p18.setIconSize(QtCore.QSize(16, 16))
        self.p18.setObjectName("p18")
        self.p14 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(14))
        self.p14.setGeometry(QtCore.QRect(350, 200, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p14.setFont(font)
        self.p14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p14.setIconSize(QtCore.QSize(16, 16))
        self.p14.setObjectName("p14")
        self.p12 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(12))
        self.p12.setGeometry(QtCore.QRect(190, 200, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p12.setFont(font)
        self.p12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p12.setIconSize(QtCore.QSize(16, 16))
        self.p12.setObjectName("p12")
        self.p17 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(17))
        self.p17.setGeometry(QtCore.QRect(590, 200, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p17.setFont(font)
        self.p17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p17.setIconSize(QtCore.QSize(16, 16))
        self.p17.setObjectName("p17")
        self.p13 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(13))
        self.p13.setGeometry(QtCore.QRect(270, 200, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p13.setFont(font)
        self.p13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p13.setIconSize(QtCore.QSize(16, 16))
        self.p13.setObjectName("p13")
        self.p16 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(16))
        self.p16.setGeometry(QtCore.QRect(510, 200, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p16.setFont(font)
        self.p16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p16.setIconSize(QtCore.QSize(16, 16))
        self.p16.setObjectName("p16")
        self.p15 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(15))
        self.p15.setGeometry(QtCore.QRect(430, 200, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p15.setFont(font)
        self.p15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p15.setIconSize(QtCore.QSize(16, 16))
        self.p15.setObjectName("p15")
        self.p11 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(11))
        self.p11.setGeometry(QtCore.QRect(110, 200, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p11.setFont(font)
        self.p11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p11.setIconSize(QtCore.QSize(16, 16))
        self.p11.setObjectName("p11")
        self.p24 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(24))
        self.p24.setGeometry(QtCore.QRect(430, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p24.setFont(font)
        self.p24.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p24.setIconSize(QtCore.QSize(16, 16))
        self.p24.setObjectName("p24")
        self.p21 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(21))
        self.p21.setGeometry(QtCore.QRect(190, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p21.setFont(font)
        self.p21.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p21.setIconSize(QtCore.QSize(16, 16))
        self.p21.setObjectName("p21")
        self.p19 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(19))
        self.p19.setGeometry(QtCore.QRect(30, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p19.setFont(font)
        self.p19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p19.setIconSize(QtCore.QSize(16, 16))
        self.p19.setObjectName("p19")
        self.p26 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(26))
        self.p26.setGeometry(QtCore.QRect(590, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p26.setFont(font)
        self.p26.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p26.setIconSize(QtCore.QSize(16, 16))
        self.p26.setObjectName("p26")
        self.p22 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(22))
        self.p22.setGeometry(QtCore.QRect(270, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p22.setFont(font)
        self.p22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p22.setIconSize(QtCore.QSize(16, 16))
        self.p22.setObjectName("p22")
        self.p20 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(20))
        self.p20.setGeometry(QtCore.QRect(110, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p20.setFont(font)
        self.p20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p20.setIconSize(QtCore.QSize(16, 16))
        self.p20.setObjectName("p20")
        self.p23 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(23))
        self.p23.setGeometry(QtCore.QRect(350, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p23.setFont(font)
        self.p23.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p23.setIconSize(QtCore.QSize(16, 16))
        self.p23.setObjectName("p23")
        self.p27 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(27))
        self.p27.setGeometry(QtCore.QRect(670, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p27.setFont(font)
        self.p27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p27.setIconSize(QtCore.QSize(16, 16))
        self.p27.setObjectName("p27")
        self.p25 = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.press_it(25))
        self.p25.setGeometry(QtCore.QRect(510, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.p25.setFont(font)
        self.p25.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.p25.setIconSize(QtCore.QSize(16, 16))
        self.p25.setObjectName("p25")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 360, 101, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it(28))
        self.pushButton.setGeometry(QtCore.QRect(620, 10, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 30, 571, 61))
        self.lineEdit.setObjectName("lineEdit")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("-")
        self.lineEdit.setReadOnly(True)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget,clicked = self.CopyToClipboard)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 60, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 780, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Math Keyboard"))
        self.p1.setText(_translate("MainWindow", "⇒"))
        self.p2.setText(_translate("MainWindow", "~"))
        self.p6.setText(_translate("MainWindow", "∂"))
        self.p5.setText(_translate("MainWindow", "∁"))
        self.p4.setText(_translate("MainWindow", "∀"))
        self.p3.setText(_translate("MainWindow", "±"))
        self.p8.setText(_translate("MainWindow", "≤"))
        self.p9.setText(_translate("MainWindow", "≥"))
        self.p7.setText(_translate("MainWindow", "∃"))
        self.p10.setText(_translate("MainWindow", "⇔"))
        self.p18.setText(_translate("MainWindow", "∝"))
        self.p14.setText(_translate("MainWindow", "∏"))
        self.p12.setText(_translate("MainWindow", "∅"))
        self.p17.setText(_translate("MainWindow", "∘"))
        self.p13.setText(_translate("MainWindow", "∆"))
        self.p16.setText(_translate("MainWindow", "≡"))
        self.p15.setText(_translate("MainWindow", "∣"))
        self.p11.setText(_translate("MainWindow", "⇏"))
        self.p24.setText(_translate("MainWindow", "∠"))
        self.p21.setText(_translate("MainWindow", "∈"))
        self.p19.setText(_translate("MainWindow", "⅀"))
        self.p26.setText(_translate("MainWindow", "∬"))
        self.p22.setText(_translate("MainWindow", "∉"))
        self.p20.setText(_translate("MainWindow", "≠"))
        self.p23.setText(_translate("MainWindow", "∞"))
        self.p27.setText(_translate("MainWindow", "∭"))
        self.p25.setText(_translate("MainWindow", "∫"))
        self.label.setText(_translate("MainWindow", "Ege Güler - 2022"))
        self.pushButton.setText(_translate("MainWindow", "Clear"))
        self.pushButton_2.setText(_translate("MainWindow", "Copy"))

    def press_it(self, pressed):
        symbols = [u"\u21D2", u"\u223C", u"\u2213", u"\u2200", u"\u2201", u"\u2203", u"\u2202", u"\u2264",
                   u"\u2265", u"\u21D4", u"\u21CF", u"\u2205",
                   u"\u2206", u"\u220F", u"\u2223", u"\u2261", u"\u2218", u"\u221D", u"\u2211", u"\u2260",
                   u"\u2208", u"\u2209", u"\u221E", u"\u2220"
            , u"\u222B", u"\u222C", u"\u222D", "-"]
        self.lineEdit.setText(symbols[pressed - 1])

    def CopyToClipboard(self):
        cb = QtWidgets.QApplication.clipboard()
        cb.clear(mode = cb.Clipboard)
        cb.setText(self.lineEdit.text(), mode = cb.Clipboard)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
